// Sample vendor data for marketplace
export const vendors = [
  {
    id: 1,
    name: "EcoTrust Carbon",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-E5IxSf55dWWTL5duYQGB60kZAtVz0k.png",
    pricePerUnit: 25,
    description: "Verified carbon credits from renewable energy projects",
    rating: 4.5,
    totalSales: 1500,
    location: "Ngong, Kenya",
    projectType: "Wind Energy",
    verification: "Gold Standard",
    availableCredits: 5000,
    detailedDescription: `EcoTrust Carbon specializes in generating high-quality carbon credits through wind energy projects in Ngong Hills. Our credits are verified by Gold Standard and represent real, measurable carbon reductions.`,
  },
  {
    id: 2,
    name: "Green Forest Initiative",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-DueVdDLdElvzEJB0ZaQ4F0vgGEqoLL.png",
    pricePerUnit: 30,
    description: "Forest conservation and reforestation carbon credits",
    rating: 4.8,
    totalSales: 2200,
    location: "Nyeri, Kenya",
    projectType: "Forest Conservation",
    verification: "Verra VCS",
    availableCredits: 3500,
    detailedDescription: `The Green Forest Initiative protects and restores critical forest ecosystems in Nyeri County. Our projects not only capture carbon but also preserve biodiversity and support local communities.`,
  },
  {
    id: 3,
    name: "Solar Credit Solutions",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-B4LYA4Ndv4D3jvxGBx1pYilYilyHhR.png",
    pricePerUnit: 22,
    description: "Carbon credits from large-scale solar installations",
    rating: 4.3,
    totalSales: 1800,
    location: "Wajir, Kenya",
    projectType: "Solar Energy",
    verification: "Gold Standard",
    availableCredits: 7500,
    detailedDescription: `Solar Credit Solutions operates utility-scale solar installations in Wajir County. Our projects generate clean energy and verifiable carbon credits while supporting local economic development.`,
  },
  {
    id: 4,
    name: "Ocean Carbon Capture",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-9ZZJiHFylN0ZZz3HTAK3geh8jRCdQ7.png",
    pricePerUnit: 35,
    description: "Blue carbon credits from marine ecosystem conservation",
    rating: 4.6,
    totalSales: 1200,
    location: "Lamu, Kenya",
    projectType: "Marine Conservation",
    verification: "Plan Vivo",
    availableCredits: 2000,
    detailedDescription: `Ocean Carbon Capture protects and restores marine ecosystems in Lamu County. These "blue carbon" projects provide critical habitat for marine life while sequestering significant amounts of carbon.`,
  },
  {
    id: 5,
    name: "Wind Power Credits",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-E5IxSf55dWWTL5duYQGB60kZAtVz0k.png",
    pricePerUnit: 28,
    description: "Credits from wind farm projects",
    rating: 4.4,
    totalSales: 1950,
    location: "Naivasha, Kenya",
    projectType: "Wind Energy",
    verification: "Gold Standard",
    availableCredits: 4500,
    detailedDescription: `Wind Power Credits generates carbon credits through our network of wind farms in Naivasha. Our projects provide clean energy to thousands of homes while offsetting significant carbon emissions.`,
  },
  {
    id: 6,
    name: "Sustainable Agriculture Co",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-DueVdDLdElvzEJB0ZaQ4F0vgGEqoLL.png",
    pricePerUnit: 27,
    description: "Credits from sustainable farming practices",
    rating: 4.2,
    totalSales: 1600,
    location: "Juja, Kenya",
    projectType: "Agriculture",
    verification: "Verra VCS",
    availableCredits: 3000,
    detailedDescription: `Sustainable Agriculture Co works with farmers in Juja to implement regenerative agriculture practices that sequester carbon in soil. Our projects improve soil health, reduce chemical inputs, and create additional income for farmers.`,
  },
]

// Sample users for admin dashboard
export const demoUsers = [
  {
    id: 1,
    name: "Joe Smith",
    email: "joe@example.com",
    role: "buyer",
    joinDate: "2024-01-15",
    totalPurchases: 5,
    creditsBought: 1000,
    location: "Nairobi, Kenya",
    preferences: {
      projectTypes: ["Renewable Energy", "Forest Conservation"],
      maxPricePerUnit: 30,
    },
  },
  {
    id: 2,
    name: "Laura Chen",
    email: "laura@example.com",
    role: "vendor",
    joinDate: "2023-12-01",
    totalSales: 25,
    creditsAvailable: 5000,
    creditsSold: 3000,
    location: "Mombasa, Kenya",
    companyName: "EcoTrust Carbon",
  },
]

// Sample orders for buyer dashboard
export const demoOrders = [
  {
    id: 1,
    date: "2024-02-24",
    vendor: "EcoTrust Carbon",
    amount: 100,
    price: 2500,
    status: "completed",
    projectType: "Wind Energy",
    verification: "Gold Standard",
  },
  {
    id: 2,
    date: "2024-02-23",
    vendor: "Green Forest Initiative",
    amount: 50,
    price: 1500,
    status: "pending",
    projectType: "Forest Conservation",
    verification: "Verra VCS",
  },
]

// Sample listings for vendor dashboard
export const demoListings = [
  {
    id: 1,
    title: "Wind Energy Credits - Ngong Hills",
    price: 25,
    available: 1000,
    sold: 500,
    projectType: "Wind Energy",
    verification: "Gold Standard",
    location: "Ngong, Kenya",
    description: "Carbon credits from our wind energy projects in Ngong Hills",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-E5IxSf55dWWTL5duYQGB60kZAtVz0k.png",
  },
  {
    id: 2,
    title: "Solar Farm Credits - Wajir",
    price: 30,
    available: 2000,
    sold: 800,
    projectType: "Solar Energy",
    verification: "Verra VCS",
    location: "Wajir, Kenya",
    description: "Credits from our solar installation in Wajir County",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-B4LYA4Ndv4D3jvxGBx1pYilYilyHhR.png",
  },
]

// Sample admin dashboard stats
export const demoAdminStats = {
  overview: {
    totalUsers: 1250,
    totalVendors: 45,
    totalTransactions: 3500,
    totalVolume: 125000,
  },
  recentActivity: [
    {
      id: 1,
      type: "New Vendor Registration",
      name: "Green Solutions Inc",
      date: "2024-02-24",
      status: "Pending Approval",
    },
    {
      id: 2,
      type: "Large Transaction",
      name: "Corporate Buyer LLC",
      date: "2024-02-23",
      status: "Completed",
      amount: 10000,
    },
  ],
  marketMetrics: {
    averagePrice: 28.5,
    totalCreditsAvailable: 50000,
    totalCreditsSold: 35000,
    monthlyGrowth: 15,
  },
}

