// Sample vendor data for marketplace
export const vendors = [
  {
    id: 1,
    name: "EcoTrust Carbon",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-E5IxSf55dWWTL5duYQGB60kZAtVz0k.png",
    pricePerUnit: 25,
    description: "Verified carbon credits from renewable energy projects",
    rating: 4.5,
    totalSales: 1500,
    location: "Ngong, Kenya",
    projectType: "Wind Energy",
    verification: "Gold Standard",
    availableCredits: 5000,
    detailedDescription: `EcoTrust Carbon specializes in generating high-quality carbon credits through wind energy projects in Ngong Hills. Our credits are verified by Gold Standard and represent real, measurable carbon reductions.`,
  },
  {
    id: 2,
    name: "Green Forest Initiative",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-DueVdDLdElvzEJB0ZaQ4F0vgGEqoLL.png",
    pricePerUnit: 30,
    description: "Forest conservation and reforestation carbon credits",
    rating: 4.8,
    totalSales: 2200,
    location: "Nyeri, Kenya",
    projectType: "Forest Conservation",
    verification: "Verra VCS",
    availableCredits: 3500,
    detailedDescription: `The Green Forest Initiative protects and restores critical forest ecosystems in Nyeri County. Our projects not only capture carbon but also preserve biodiversity and support local communities.`,
  },
  {
    id: 3,
    name: "Clean Cookstove Solutions",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-EeaKDnLHmJBSTAKTboP0mAB9C5MvXd.png",
    pricePerUnit: 20,
    description: "Carbon credits from efficient cookstove distribution",
    rating: 4.6,
    totalSales: 1800,
    location: "Kisumu, Kenya",
    projectType: "Energy Efficiency",
    verification: "Gold Standard",
    availableCredits: 4000,
    detailedDescription: `Our efficient cookstove program reduces wood fuel consumption and indoor air pollution while generating verified carbon credits. Each stove saves approximately 2 tons of CO2 emissions annually.`,
  },
  {
    id: 4,
    name: "Carbon Capture Technologies",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-kc1JMV7tjjDV6wXW4lI33O1YAzSVUi.png",
    pricePerUnit: 45,
    description: "Industrial-scale carbon capture and storage",
    rating: 4.7,
    totalSales: 1200,
    location: "Mombasa, Kenya",
    projectType: "Carbon Capture",
    verification: "Verra VCS",
    availableCredits: 8000,
    detailedDescription: `Our state-of-the-art carbon capture facility removes CO2 directly from industrial emissions and stores it safely underground, providing high-quality carbon credits with permanent storage.`,
  },
  {
    id: 5,
    name: "EV Infrastructure Fund",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-puklckgy5DsHLRw08B03awY9N61148.png",
    pricePerUnit: 35,
    description: "Credits from EV charging infrastructure",
    rating: 4.4,
    totalSales: 900,
    location: "Nairobi, Kenya",
    projectType: "Transportation",
    verification: "Gold Standard",
    availableCredits: 3000,
    detailedDescription: `We generate carbon credits by building and operating EV charging infrastructure, accelerating the transition to electric mobility in East Africa.`,
  },
  {
    id: 6,
    name: "Blue Carbon Initiative",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-hZIDAPyyizl7i1Ajc41OspIU2WS2aj.png",
    pricePerUnit: 40,
    description: "Seagrass and marine ecosystem credits",
    rating: 4.9,
    totalSales: 800,
    location: "Lamu, Kenya",
    projectType: "Blue Carbon",
    verification: "Plan Vivo",
    availableCredits: 2500,
    detailedDescription: `Our blue carbon projects protect and restore vital marine ecosystems, including seagrass meadows and mangroves, which are powerful natural carbon sinks.`,
  },
  {
    id: 7,
    name: "Smart Mobility Network",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-lp2zb1Y9jAPjGmtTUVUq7n0YzpguRD.png",
    pricePerUnit: 25,
    description: "Carpooling and ride-sharing credits",
    rating: 4.3,
    totalSales: 1100,
    location: "Nairobi, Kenya",
    projectType: "Transportation",
    verification: "Gold Standard",
    availableCredits: 5000,
    detailedDescription: `We reduce transport emissions through our innovative carpooling platform, connecting commuters and reducing single-occupancy vehicle trips.`,
  },
  {
    id: 8,
    name: "Biogas Solutions Kenya",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-YjRXAbIQWF7tR9xGNom8ZdplNzEgH0.png",
    pricePerUnit: 28,
    description: "Agricultural waste to energy projects",
    rating: 4.5,
    totalSales: 1400,
    location: "Nakuru, Kenya",
    projectType: "Waste to Energy",
    verification: "Gold Standard",
    availableCredits: 4500,
    detailedDescription: `Our biogas projects convert agricultural waste into clean energy, reducing methane emissions and providing renewable energy to local communities.`,
  },
  {
    id: 9,
    name: "Agroforestry Alliance",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-jLWmVrWwyEGZzVzkJM1HT0SetlEoYU.png",
    pricePerUnit: 32,
    description: "Integrated farming and forestry credits",
    rating: 4.7,
    totalSales: 1600,
    location: "Kitale, Kenya",
    projectType: "Agroforestry",
    verification: "Verra VCS",
    availableCredits: 6000,
    detailedDescription: `We work with farmers to integrate trees into agricultural landscapes, enhancing carbon sequestration while improving crop yields and biodiversity.`,
  },
]

// Sample users for admin dashboard
export const demoUsers = [
  {
    id: 1,
    name: "Joe Smith",
    email: "joe@example.com",
    role: "buyer",
    joinDate: "2024-01-15",
    totalPurchases: 5,
    creditsBought: 1000,
    location: "Nairobi, Kenya",
    preferences: {
      projectTypes: ["Renewable Energy", "Forest Conservation"],
      maxPricePerUnit: 30,
    },
  },
  {
    id: 2,
    name: "Laura Chen",
    email: "laura@example.com",
    role: "vendor",
    joinDate: "2023-12-01",
    totalSales: 25,
    creditsAvailable: 5000,
    creditsSold: 3000,
    location: "Mombasa, Kenya",
    companyName: "EcoTrust Carbon",
  },
]

// Sample orders for buyer dashboard
export const demoOrders = [
  {
    id: 1,
    date: "2024-02-24",
    vendor: "EcoTrust Carbon",
    amount: 100,
    price: 2500,
    status: "completed",
    projectType: "Wind Energy",
    verification: "Gold Standard",
  },
  {
    id: 2,
    date: "2024-02-23",
    vendor: "Green Forest Initiative",
    amount: 50,
    price: 1500,
    status: "pending",
    projectType: "Forest Conservation",
    verification: "Verra VCS",
  },
]

// Sample listings for vendor dashboard
export const demoListings = [
  {
    id: 1,
    title: "Wind Energy Credits - Ngong Hills",
    price: 25,
    available: 1000,
    sold: 500,
    projectType: "Wind Energy",
    verification: "Gold Standard",
    location: "Ngong, Kenya",
    description: "Carbon credits from our wind energy projects in Ngong Hills",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-E5IxSf55dWWTL5duYQGB60kZAtVz0k.png",
  },
  {
    id: 2,
    title: "Solar Farm Credits - Wajir",
    price: 30,
    available: 2000,
    sold: 800,
    projectType: "Solar Energy",
    verification: "Verra VCS",
    location: "Wajir, Kenya",
    description: "Credits from our solar installation in Wajir County",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-B4LYA4Ndv4D3jvxGBx1pYilYilyHhR.png",
  },
]

// Sample admin dashboard stats
export const demoAdminStats = {
  overview: {
    totalUsers: 1250,
    totalVendors: 45,
    totalTransactions: 3500,
    totalVolume: 125000,
  },
  recentActivity: [
    {
      id: 1,
      type: "New Vendor Registration",
      name: "Green Solutions Inc",
      date: "2024-02-24",
      status: "Pending Approval",
    },
    {
      id: 2,
      type: "Large Transaction",
      name: "Corporate Buyer LLC",
      date: "2024-02-23",
      status: "Completed",
      amount: 10000,
    },
  ],
  marketMetrics: {
    averagePrice: 28.5,
    totalCreditsAvailable: 50000,
    totalCreditsSold: 35000,
    monthlyGrowth: 15,
  },
}

// Demo blockchain transactions
export const blockchainTransactions = [
  {
    id: 1,
    hash: "0x1234...5678",
    from: "0xABCD...EFGH",
    to: "0x9876...5432",
    amount: 25000,
    type: "Carbon Sale",
    timestamp: "2024-02-26 14:30:45",
    status: "Confirmed",
    credits: 1000,
  },
  {
    id: 2,
    hash: "0x8765...4321",
    from: "0x1111...2222",
    to: "0x3333...4444",
    amount: 15000,
    type: "Chama Deduction",
    timestamp: "2024-02-26 13:15:22",
    status: "Confirmed",
    credits: 600,
  },
  {
    id: 3,
    hash: "0x5555...6666",
    from: "0x7777...8888",
    to: "0x9999...0000",
    amount: 35000,
    type: "Payment to Vendor",
    timestamp: "2024-02-26 12:45:10",
    status: "Confirmed",
    credits: 1400,
  },
  {
    id: 4,
    hash: "0xAAAA...BBBB",
    from: "0xCCCC...DDDD",
    to: "0xEEEE...FFFF",
    amount: 5000,
    type: "Group Pool Contribution",
    timestamp: "2024-02-26 11:30:15",
    status: "Confirmed",
    credits: 200,
  },
  {
    id: 5,
    hash: "0x2468...1357",
    from: "0xFEDC...BA98",
    to: "0x1357...2468",
    amount: 12500,
    type: "Carbon Sale",
    timestamp: "2024-02-26 10:15:30",
    status: "Confirmed",
    credits: 500,
  },
]

